5.0 entity generalization
shikshalokam/ml-survey-service pull request #86
Opened 2022-08-09 03:52 UTC by VISHNUDAS-tunerlabs

2022-08-22 15:24 UTC, aks30 requested changes
Reviewed on 22 Aug.

2022-08-22 15:24 UTC, aks30 commented on controllers/v1/observationsController.js
> +    let uniqueEntities = [];
@VISHNUDAS-tunerlabs as discussed this is not required. Also please make variable name changes.

2022-08-23 01:54 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/observationSubmissionsController.js
> +        let entityResult = entitiesDocument.data;
@aks30 returning object argument is not needed. only using at two places and they require object in return.

2022-08-23 02:45 UTC, VISHNUDAS-tunerlabs commented on module/entities/helper.js
> +
@aks30 entity data contain id not _id, it does not contain districtName also

2022-08-23 03:56 UTC, VISHNUDAS-tunerlabs commented on module/entities/helper.js
> +
@aks30 we have id instead _id. districtName not available in learners search

2022-08-23 05:55 UTC, VISHNUDAS-tunerlabs commented on module/entities/helper.js
> +                if (gen.utils.checkIfValidUUID(entity)) {
@aks30 old code -old code we were checking with entityId. But now we need to check uuid and code (for school)

2022-08-23 06:19 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/observationSubmissionsController.js
> +          entityId: entityDocument.id,
@aks30 change made.

2022-08-23 06:32 UTC, VISHNUDAS-tunerlabs commented on module/observations/helper.js
>              },["entities","entityType"]);
@aks30 ok

2022-08-23 10:01 UTC, VISHNUDAS-tunerlabs commented on module/observations/helper.js
> +                        _id : currentEntities.id,
@aks30 added.

2022-08-24 08:02 UTC, aks30 requested changes
Reviewed on 24 Aug

2022-09-05 02:00 UTC, merged